In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import pandas as dataframe
#from stats import median
import plotly.plotly as py
import plotly.figure_factory as ff
from scipy import stats
import numpy as np
import requests
import time
import json
import plotly
from config_plotly import key
plotly.tools.set_credentials_file(username='pk94978', api_key = 'v1NQBDV5zZbzSQvt0Zxc')

# read excel file
census2010 = pd.read_csv("census2010.csv")
obesity_cdc = pd.read_csv("cdc_obesity.csv")
df_sample = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/laucnty16.csv')
df_sample

,LAUS Code,State FIPS Code,County FIPS Code,County Name/State Abbreviation,Year,Labor Force,Employed,Unemployed,Unemployment Rate (%)
0,CN0100100000000,1,1,"Autauga County, AL",2016,"25,649","24,297","1,352",5.3
1,CN0100300000000,1,3,"Baldwin County, AL",2016,"89,931","85,061","4,870",5.4
2,CN0100500000000,1,5,"Barbour County, AL",2016,"8,302","7,584",718,8.6
3,CN0100700000000,1,7,"Bibb County, AL",2016,"8,573","8,004",569,6.6
4,CN0100900000000,1,9,"Blount County, AL",2016,"24,525","23,171","1,354",5.5
5,CN0101100000000,1,11,"Bullock County, AL",2016,"4,811","4,466",345,7.2
6,CN0101300000000,1,13,"Butler County, AL",2016,"9,132","8,481",651,7.1
7,CN0101500000000,1,15,"Calhoun County, AL",2016,"45,794","42,727","3,067",6.7
8,CN0101700000000,1,17,"Chambers County, AL",2016,"15,134","14,295",839,5.5
9,CN0101900000000,1,19,"Cherokee County, AL",2016,"11,163","10,581",582,5.2
10,CN0102100000000,1,21,"Chilton County, AL",2016,"19,153","18,077","1,076",5.6
11,CN0102300000000,1,23,"Choctaw County, AL",2016,"4,300","3,918",382,8.9
12,CN0102500000000,1,25,"Clarke County, AL",2016,"8,011","7,118",893,11.1
13,CN0102700000000,1,27,"Clay County, AL",2016,"5,558","5,216",342,6.2
14,CN0102900000000,1,29,"Cleburne County, AL",2016,"5,831","5,476",355,6.1
15,CN0103100000000,1,31,"Coffee County, AL",2016,"20,402","19,167","1,235",6.1
16,CN0103300000000,1,33,"Colbert County, AL",2016,"23,707","22,045","1,662",7.0
17,CN0103500000000,1,35,"Conecuh County, AL",2016,"4,593","4,197",396,8.6
18,CN0103700000000,1,37,"Coosa County, AL",2016,"4,444","4,171",273,6.1
19,CN0103900000000,1,39,"Covington County, AL",2016,"15,392","14,315","1,077",7.0
20,CN0104100000000,1,41,"Crenshaw County, AL",2016,"6,451","6,063",388,6.0
21,CN0104300000000,1,43,"Cullman County, AL",2016,"37,715","35,792","1,923",5.1
22,CN0104500000000,1,45,"Dale County, AL",2016,"20,078","18,890","1,188",5.9
23,CN0104700000000,1,47,"Dallas County, AL",2016,"15,530","14,071","1,459",9.4
24,CN0104900000000,1,49,"DeKalb County, AL",2016,"29,016","27,216","1,800",6.2
25,CN0105100000000,1,51,"Elmore County, AL",2016,"36,726","34,917","1,809",4.9
26,CN0105300000000,1,53,"Escambia County, AL",2016,"14,633","13,648",985,6.7
27,CN0105500000000,1,55,"Etowah County, AL",2016,"43,887","41,269","2,618",6.0
28,CN0105700000000,1,57,"Fayette County, AL",2016,"6,543","6,087",456,7.0
29,CN0105900000000,1,59,"Franklin County, AL",2016,"13,723","12,886",837,6.1
...,...,...,...,...,...,...,...,...,...
3189,CN7209500000000,72,95,"Maunabo Municipio, PR",2016,"3,045","2,483",562,18.5
3190,CN7209700000000,72,97,"Mayaguez Municipio, PR",2016,"23,367","20,158","3,209",13.7
3191,CN7209900000000,72,99,"Moca Municipio, PR",2016,"10,794","9,122","1,672",15.5
3192,CN7210100000000,72,101,"Morovis Municipio, PR",2016,"8,075","6,983","1,092",13.5
3193,CN7210300000000,72,103,"Naguabo Municipio, PR",2016,"8,035","7,037",998,12.4
3194,CN7210500000000,72,105,"Naranjito Municipio, PR",2016,"7,253","6,308",945,13.0
3195,CN7210700000000,72,107,"Orocovis Municipio, PR",2016,"5,230","4,419",811,15.5
3196,CN7210900000000,72,109,"Patillas Municipio, PR",2016,"4,880","3,876","1,004",20.6
3197,CN7211100000000,72,111,"Penuelas Municipio, PR",2016,"6,170","5,148","1,022",16.6
3198,CN7211300000000,72,113,"Ponce Municipio, PR",2016,"48,145","41,677","6,468",13.4
3199,CN7211500000000,72,115,"Quebradillas Municipio, PR",2016,"6,109","5,131",978,16.0
3200,CN7211700000000,72,117,"Rincon Municipio, PR",2016,"4,635","3,909",726,15.7
3201,CN7211900000000,72,119,"Rio Grande Municipio, PR",2016,"17,092","15,290","1,802",10.5
3202,CN7212100000000,72,121,"Sabana Grande Municipio, PR",2016,"6,506","5,474","1,032",15.9
3203,CN7212300000000,72,123,"Salinas Municipio, PR",2016,"7,623","5,967","1,656",21.7
3204,CN7212500000000,72,125,"San German Municipio, PR",2016,"10,464","8,880","1,584",15.1
3205,CN7212700000000,72,127,"San Juan Municipio, PR",2016,"136,252","125,544","10,708",7.9
3206,CN7212900000000,72,129,"San Lorenzo Municipio, PR",2016,"11,914","10,412","1,502",12.6
3207,CN7213100000000,72,131,"San Sebastian Municipio, PR",2016,"10,819","8,773","2,046",18.9
3208,CN7213300000000,72,133,"Santa Isabel Municipio, PR",2016,"9,912","8,248","1,664",16.8
3209,CN7213500000000,72,135,"Toa Alta Municipio, PR",2016,"26,319","24,112","2,207",8.4
3210,CN7213700000000,72,137,"Toa Baja Municipio, PR",2016,"29,964","27,290","2,674",8.9
3211,CN7213900000000,72,139,"Trujillo Alto Municipio, PR",2016,"27,263","25,304","1,959",7.2
3212,CN7214100000000,72,141,"Utuado Municipio, PR",2016,"6,968","5,889","1,079",15.5
3213,CN7214300000000,72,143,"Vega Alta Municipio, PR",2016,"9,841","8,703","1,138",11.6
3214,CN7214500000000,72,145,"Vega Baja Municipio, PR",2016,"13,812","11,894","1,918",13.9
3215,CN7214700000000,72,147,"Vieques Municipio, PR",2016,"3,287","2,939",348,10.6
3216,CN7214900000000,72,149,"Villalba Municipio, PR",2016,"7,860","6,273","1,587",20.2
3217,CN7215100000000,72,151,"Yabucoa Municipio, PR",2016,"9,137","7,591","1,546",16.9
3218,CN7215300000000,72,153,"Yauco Municipio, PR",2016,"10,815","8,783","2,032",18.8

In [2]:
key

'v1NQBDV5zZbzSQvt0Zxc'

In [3]:
# CDC Data Clean-up: format to columns to string or floats
census2010.rename(columns={'Density per square mile of land area - Population':'density_2010_psq','Population': 'Pop_2010','Target Geo Id2':'FIPS Codes'},inplace=True)

In [4]:
census2010['Pop_2010'] = pd.to_numeric(census2010['Pop_2010'],errors='coerce')
census2010['FIPS Codes'] = census2010['FIPS Codes'].astype(str).replace('\.0', '', regex=True)
census2010['FIPS Codes'] = census2010['FIPS Codes'].apply('{:0>5}'.format)
census2010.head()

,Id,Id2,Geography,Target Geo Id,FIPS Codes,Geographic area,Geographic area.1,Pop_2010,Housing units,Area in square miles - Total area,Area in square miles - Water area,Area in square miles - Land area,density_2010_psq,Density per square mile of land area - Housing units
0,0100000US,NaN,United States,0400000US01,00001,United States - Alabama,Alabama,NaN,2171853(r15032),52420.07,1774.74,50645.33,94.4,42.9
1,0100000US,NaN,United States,0500000US01001,01001,United States - Alabama - Autauga County,Autauga County,54571.0,22135,604.39,9.95,594.44,91.8,37.2
2,0100000US,NaN,United States,0500000US01003,01003,United States - Alabama - Baldwin County,Baldwin County,182265.0,104061,2027.31,437.53,1589.78,114.6,65.5
3,0100000US,NaN,United States,0500000US01005,01005,United States - Alabama - Barbour County,Barbour County,27457.0,11829(r15033),904.52,19.64,884.88,31.0,13.4
4,0100000US,NaN,United States,0500000US01007,01007,United States - Alabama - Bibb County,Bibb County,22915.0,8981,626.17,3.59,622.58,36.8,14.4

In [5]:
census2010.dtypes

Id                                                       object
Id2                                                     float64
Geography                                                object
Target Geo Id                                            object
FIPS Codes                                               object
Geographic area                                          object
Geographic area.1                                        object
Pop_2010                                                float64
Housing units                                            object
Area in square miles - Total area                       float64
Area in square miles - Water area                       float64
Area in square miles - Land area                        float64
density_2010_psq                                        float64
Density per square mile of land area - Housing units    float64
dtype: object

In [6]:
#format CDC 2010 data:
obesity_cdc['percent_2010'] = pd.to_numeric(obesity_cdc['percent_2010'],errors='coerce')
obesity_cdc['number_2010'] = pd.to_numeric(obesity_cdc['number_2010'],errors='coerce')
obesity_cdc['FIPS Codes'] = obesity_cdc['FIPS Codes'].apply('{:0>5}'.format)

In [7]:
#Rename column headers
obesity_df = obesity_cdc[["State","FIPS Codes", "County","number_2010","percent_2010","number_2013","percent_2013"]]
obesity_df.head()

,State,FIPS Codes,County,number_2010,percent_2010,number_2013,percent_2013
0,Alabama,01001,Autauga County,11761.0,30.5,13513,34.1
1,Alabama,01003,Baldwin County,36348.0,26.6,40365,27.4
2,Alabama,01005,Barbour County,7743.0,37.3,9186,44.4
3,Alabama,01007,Bibb County,5884.0,34.3,6940,40.3
4,Alabama,01009,Blount County,12690.0,30.4,14768,34.6

In [8]:
#merge 2010 Census and CDC data
merged_tbl = pd.merge(census2010, obesity_df, on="FIPS Codes")
merged_tbl.dtypes

Id                                                       object
Id2                                                     float64
Geography                                                object
Target Geo Id                                            object
FIPS Codes                                               object
Geographic area                                          object
Geographic area.1                                        object
Pop_2010                                                float64
Housing units                                            object
Area in square miles - Total area                       float64
Area in square miles - Water area                       float64
Area in square miles - Land area                        float64
density_2010_psq                                        float64
Density per square mile of land area - Housing units    float64
State                                                    object
County                                                   object
number_2010                                             float64
percent_2010                                            float64
number_2013                                              object
percent_2013                                             object
dtype: object

In [9]:
#Create new df from select columns in merged_tbl_2010 data
main_df = merged_tbl[["FIPS Codes","State", "County","Pop_2010","density_2010_psq","percent_2010"]]
main_df.head()

,FIPS Codes,State,County,Pop_2010,density_2010_psq,percent_2010
0,01001,Alabama,Autauga County,54571.0,91.8,30.5
1,01003,Alabama,Baldwin County,182265.0,114.6,26.6
2,01005,Alabama,Barbour County,27457.0,31.0,37.3
3,01007,Alabama,Bibb County,22915.0,36.8,34.3
4,01009,Alabama,Blount County,57322.0,88.9,30.4

In [10]:
#Plotpoly USA - Population Density
# df_sample['State FIPS Code'] = df_sample['State FIPS Code'].apply(lambda x: str(x).zfill(2))
# df_sample['County FIPS Code'] = df_sample['County FIPS Code'].apply(lambda x: str(x).zfill(3))
# df_sample['FIPS'] = df_sample['State FIPS Code'] + df_sample['County FIPS Code']

colorscale = ["#f7fbff","#ebf3fb","#deebf7","#d2e3f3","#c6dbef","#b3d2e9","#9ecae1",
              "#85bcdb","#6baed6","#57a0ce","#4292c6","#3082be","#2171b5","#1361a9",
              "#08519c","#0b4083","#08306b"]
endpts = list(np.linspace(15, 130, len(colorscale) - 1))
fips = main_df['FIPS Codes'].tolist()
values = main_df['density_2010_psq'].tolist()


fig = ff.create_choropleth(
    fips=fips, values=values,
    binning_endpoints=endpts,
    colorscale=colorscale,
    show_state_data=False,
    show_hover=True, centroid_marker={'opacity': 0},
    asp=2.9, title='USA by Population Density',
    legend_title='% of Density'
)
py.iplot(fig, filename='choropleth_full_usa')

C:\Users\pk949\Anaconda3\envs\PythonData\lib\site-packages\pandas\core\frame.py:6692: FutureWarning:

Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

High five! You successfully sent some data to your account on plotly. View your plot in your browser at https://plot.ly/~pk94978/0 or inside your plot.ly account where it is named 'choropleth_full_usa'

C:\Users\pk949\Anaconda3\envs\PythonData\lib\site-packages\chart_studio\api\v1\clientresp.py:44: UserWarning:

Estimated Draw Time Slow

C:\Users\pk949\Anaconda3\envs\PythonData\lib\site-packages\IPython\core\display.py:689: UserWarning:

Consider using IPython.display.IFrame instead

In [46]:
#plt.savefig("2010 USA Population Density Per Square Mile.png")

In [47]:
#Plotpoly USA - Heat Map of the Diabetic Obese Population
# df_sample['State FIPS Code'] = df_sample['State FIPS Code'].apply(lambda x: str(x).zfill(2))
# df_sample['County FIPS Code'] = df_sample['County FIPS Code'].apply(lambda x: str(x).zfill(3))
# df_sample['FIPS'] = df_sample['State FIPS Code'] + df_sample['County FIPS Code']

colorscale = ["#f7fbff","#ebf3fb","#deebf7","#d2e3f3","#c6dbef","#b3d2e9","#9ecae1",
              "#85bcdb","#6baed6","#57a0ce","#4292c6","#3082be","#2171b5","#1361a9",
              "#08519c","#0b4083","#08306b"]
endpts = list(np.linspace(15, 40, len(colorscale) - 1))
fips = main_df['FIPS Codes'].tolist()
values = main_df['percent_2010'].tolist()


fig = ff.create_choropleth(
    fips=fips, values=values,
    binning_endpoints=endpts,
    colorscale=colorscale,
    show_state_data=False,
    show_hover=True, centroid_marker={'opacity': 0},
    asp=2.9, title='USA - Obese Diabetic Population',
    legend_title='% Obese with Diabetes'
)
py.iplot(fig, filename='choropleth_full_usa')

High five! You successfully sent some data to your account on plotly. View your plot in your browser at https://plot.ly/~pk94978/0 or inside your plot.ly account where it is named 'choropleth_full_usa'

In [ ]:
#plt.savefig("USA - Obese Diabetic Population.png")